backend:
  name: github
  repo: Blastive/eis28-website
  branch: main 

media_folder: "images" # Saves new pictures into an images folder
public_folder: "images"

collections:
  - name: "galleries"
    label: "Photo Galleries"
    folder: "galleries" # This is where it will save the event data
    create: true
    fields:
      - {label: "Event Name", name: "title", widget: "string"}
      - {label: "Date (e.g. Spring 2027)", name: "date", widget: "string"}
      - {label: "Volume Number", name: "volume", widget: "string"}
      - {label: "Event Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      
