backend:
  name: github
  repo: Blastive/eis28-website
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "galleries"
    label: "Photo Galleries"
    files:
      - name: "eis-games"
        label: "EIS Games"
        file: "galleries/eis-games.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "fun-fair"
        label: "Fun Fair"
        file: "galleries/fun-fair.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "junior-love-day"
        label: "Junior Love Day"
        file: "galleries/junior-love-day.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "prom"
        label: "Prom '27"
        file: "galleries/prom.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "bible-camp"
        label: "Bible Camp"
        file: "galleries/bible-camp.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "field-trips"
        label: "Field Trips"
        file: "galleries/field-trips.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "junior-film-show"
        label: "Junior Film Show"
        file: "galleries/junior-film-show.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
      - name: "miscellaneous"
        label: "Miscellaneous"
        file: "galleries/miscellaneous.json"
        fields:
          - {label: "Photos", name: "photos", widget: "list", field: {label: "Photo", name: "image", widget: "image"}}
